dist: xenial
language: bash

branches:
  only: master

notifications:
  email: false

addons:
  apt:
    packages:
      - zip

env:
  global:
    - TZ: "Asia/Taipei"
    - secure: "QRW3OrLg5P6MV0vxd6u7gV5EdBCOHKDU+UkNHqOBI4ipGlUhzYbT0KU4ulBG9BUjlKrw7Ji0Wgwd4G3YyGhTXY7FJmHf3gbGVFv2Oa+eCmLEgkQPf+2lhrjTXuY7Mm3ShsOGd4HeWrx9gisKpDT5VgxQAWlULYd4SmdFtXzPCVM5pwJqCLA9KUAMuYMyG86+Ewl5NbBzmFLYAoZ9qjqyyvJazAYEtMSiWSsqnA71nI9RRnyTZjrTw4htEl0MshJz/+CwFktystAuhmpLIoaa0UY5lLyTKsWKteSlGAJjRExA/PcuPEhehXATes+iDYvcXdfxcvXJQYu9npdhHkosigaOw7yS0LSTXy5tScEFvV3ILE6j2mhmSksgpqqlZ/i/ctdgE0BjRNsebaU9KlnQUlLyh49OTPb4IjO9H2HCn8qq/zOd20hG3kInezdkBWNZ0oT+I6Rzau09Ot+SVLRplHndiFk0HMZmQY6c5sNVnbh1rVGoX2QW74gco+hoULavPB6Z140QsA8aM48o8NeTOAvtS62g3dCbtHTgizduBMeTMXcsYv3I26uQ0ZUeP8oJJ3ryVIcWQYdl4hsjE1qTbYT+XSDUcxNPf5W/K3xQfMyieF599AUB7VgpgyhIkhtlAuI98R1srkLhasWmjuoLvXBHHrlTTKT/y8BYUNvzsyQ="

script:
  - ./generate.sh

deploy:
  provider: pages
  local-dir: release
  target-branch: gh-pages
  keep-history: true
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}
  #name: Travis CI
  #email: travis.ci.build@gmail.com
  on:
    branch: master
